### ISSUE TITLE
USER STORY: Write a Review

### ISSUE THREAD

**Issue by merin86** [merin86/husman-moderna#7]
As a **site user** I can **write a review of the restaurant on the website** so that **I can share my experience and provide feedback to the restaurant and future guests**

### Acceptance Criteria:

- The website should have a dedicated "Write a Review" section accessible from the homepage.
- The review form should include fields for the user's name.
- Upon submission of the review form, the review should be displayed on the website's review page once approved by Admin/Superuser.

### Tasks

- [x] Design a user-friendly review form interface with input fields.
- [x] Develop logic to store submitted reviews in a database.
- [x] Create a view to display reviews on the website's review page.
